# Generated by Django 4.0.10 on 2023-09-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_confirmationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='confirmationcode',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='confirmationcode',
            name='user_details',
            field=models.JSONField(null=True),
        ),
    ]
